# Generated by Django 3.1.2 on 2021-04-17 02:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0009_auto_20210111_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dyno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('test', models.CharField(max_length=100)),
                ('constant', models.BooleanField(default=True)),
                ('throttle', models.IntegerField()),
                ('rpm', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
