# Generated by Django 3.1.2 on 2021-04-17 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0010_auto_20210416_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
